name: Gent Ng Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#424242'
    - '#6b6b6b'
    - '#ababab'
  brandStrength: 0.1875
  lightness: 0.8469484453089535
  saturation: 0.40331743843853474
  rhythmicContrast: 0.8231211660895497
purpose: []
