name: Gent Ng Photography
favicon: null
layout_spectrum: 0.3650512024760246
typography_spectrum: 0.6983631697949022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.33287829835899174
  lightness: 0.8469484453089535
  saturation: 0.40331743843853474
  rhythmicContrast: 0.8231211660895497
purpose: []
